config/routes.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root to: 'home#index'

  get 'activities' => 'home#index'
  get 'admin'      => 'admin/users#index',       :as => :admin
  get 'login'      => 'authentications#new',     :as => :login
  delete 'logout'  => 'authentications#destroy', :as => :logout
  get 'profile'    => 'users#show',              :as => :profile
  get 'signup'     => 'users#new',               :as => :signup

  get '/home/options',  as: :options
  get '/home/toggle',   as: :toggle
  match '/home/timeline', as: :timeline, via: [:get, :put, :post]
  match '/home/timezone', as: :timezone, via: [:get, :put, :post]
  post '/home/redraw',   as: :redraw

  resource :authentication, except: [:index, :edit]
  resources :comments,       except: [:new, :show]
  resources :emails,         only: [:destroy]
  resources :passwords,      only: [:new, :create, :edit, :update]

  resources :accounts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
      get :autocomplete_account_name
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: [:patch, :put]
      put :reject
    end
  end

  resources :opportunities, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, id: /\d+/ do
    collection do
      post :filter
      match :auto_complete, via: [:get, :post]
    end
    member do
      put :complete
      put :uncomplete
    end
  end

  resources :users, id: /\d+/, except: [:index, :destroy] do
    member do
      get :avatar
      get :password
      match :upload_avatar, via: [:put, :patch]
      patch :change_password
      post :redraw
    end
    collection do
      match :auto_complete, via: [:get, :post]
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete, via: [:get, :post]
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, except: [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete, via: [:get, :post]
        get :options
        get :redraw
        post :sort
        get :subform
      end
    end

    resources :tags, except: [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, as: :custom_fields
    resources :fields, as: :core_fields

    resources :settings, only: :index
    resources :plugins,  only: :index
  end
end

app/models/fields/core_field.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
# == Schema Information
#
# Table name: fields
#
#  id             :integer         not null, primary key
#  type           :string(255)
#  field_group_id :integer
#  position       :integer
#  name           :string(64)
#  label          :string(128)
#  hint           :string(255)
#  placeholder    :string(255)
#  as             :string(32)
#  collection     :text
#  disabled       :boolean
#  required       :boolean
#  maxlength      :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class CoreField < Field
  # Some CoreField attributes should be read-only
  attr_readonly :name, :as, :collection
  before_destroy :error_on_destroy

  def error_on_destroy
    errors.add_to_base "Core fields cannot be deleted."
  end

  ActiveSupport.run_load_hooks(:fat_free_crm_core_field, self)
end

app/models/fields/custom_field.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
# == Schema Information
#
# Table name: fields
#
#  id             :integer         not null, primary key
#  type           :string(255)
#  field_group_id :integer
#  position       :integer
#  name           :string(64)
#  label          :string(128)
#  hint           :string(255)
#  placeholder    :string(255)
#  as             :string(32)
#  collection     :text
#  disabled       :boolean
#  required       :boolean
#  maxlength      :integer
#  created_at     :datetime
#  updated_at     :datetime
#

# Implementation Notes
#------------------------------------------------------------------------------
# Adding database columns dynamically is not usually recommended,
# and can be potentially unsafe. However, the only alternative would be static migrations,
# and we want to let users add custom fields without having to restart their server.
# We could not use the EAV model for performance reasons, since we need to retain the
# ability to filter and search across thousands of records with potentially hundreds
# of custom fields.
#
# We have solved all of the major issues:
#
# * Custom fields for view templates are dynamically generated based on normalized
#   database records in the 'fields' table, instead of ActiveRecord's cached attributes.
# * Concurrency issues are resolved by using 'method_missing' to refresh a model's column information
#   when fields are added by a separate server process.
# * The custom field can be renamed or deleted, but database columns are never renamed or destroyed.
#   A rake task can be run to purge any orphaned columns.
# * Custom field types can only be changed if the database can support the transition.
#   For example, you can change an 'email' field to a 'string', but not to a 'datetime',
#   since changing the type of the database column would cause data to be lost.
#

class CustomField < Field
  delegate :table_name, to: :klass

  after_validation :update_column, on: :update
  before_create :add_column
  after_create :add_ransack_translation

  SAFE_DB_TRANSITIONS = {
    any: [%w(date time timestamp), %w(integer float)],
    one: { 'string' => 'text' }
  }

  def available_as
    Field.field_types.reject do |new_type, _params|
      db_transition_safety(as, new_type) == :unsafe
    end
  end

  # Extra validation that is called on this field when validation happens
  # obj is reference to parent object
  #------------------------------------------------------------------------------
  def custom_validator(obj)
    attr = name.to_sym
    obj.errors.add(attr, ::I18n.t('activerecord.errors.models.custom_field.required', field: label)) if required? && obj.send(attr).blank?
    obj.errors.add(attr, ::I18n.t('activerecord.errors.models.custom_field.maxlength', field: label)) if (maxlength.to_i > 0) && (obj.send(attr).to_s.length > maxlength.to_i)
  end

  protected

  # When changing a custom field's type, it may be necessary to
  # change the column type in the database. This method returns
  # the safety of a given transition.
  # Returns:
  #   :null   => no transition needed
  #   :safe   => transition is safe
  #   :unsafe => transition is unsafe
  #------------------------------------------------------------------------------
  def db_transition_safety(old_type, new_type = as)
    old_col, new_col = [old_type, new_type].map { |t| column_type(t).to_s }
    return :null if old_col == new_col  # no transition needed
    return :safe if SAFE_DB_TRANSITIONS[:one].any? do |start, final|
      old_col == start.to_s && new_col == final.to_s  # one-to-one
    end
    return :safe if SAFE_DB_TRANSITIONS[:any].any? do |col_set|
      [old_col, new_col].all? { |c| col_set.include?(c.to_s) }  # any-to-any
    end
    :unsafe # Else, unsafe.
  end

  # Generate column name for custom field.
  # If column name is already taken, a numeric suffix is appended.
  # Example column sequence: cf_custom, cf_custom_2, cf_custom_3, ...
  #------------------------------------------------------------------------------
  def generate_column_name
    suffix = nil
    field_name = 'cf_' + label.downcase.gsub(/[^a-z0-9]+/, '_')
    while (final_name = [field_name, suffix].compact.join('_')) &&
          klass.column_names.include?(final_name)
      suffix = (suffix || 1) + 1
    end
    final_name
  end

  # Returns options for ActiveRecord operations
  #------------------------------------------------------------------------------
  def column_options
    Field.field_types[as][:column_options] || {}
  end

  # Create a new column to hold the custom field data
  #------------------------------------------------------------------------------
  def add_column
    self.name = generate_column_name if name.blank?
    klass.connection.add_column(table_name, name, column_type, column_options)
    klass.reset_column_information
    klass.serialize_custom_fields!
  end

  # Adds custom field translation for Ransack
  def add_ransack_translation
    I18n.backend.store_translations(Setting.locale.to_sym,
                                    ransack: { attributes: { klass.model_name.singular => { name => label } } }
    )
    # Reset Ransack cache
    # Ransack::Helpers::FormBuilder.cached_searchable_attributes_for_base = {}
  end

  # Change database column type only if safe to do so
  # Note: columns will never be renamed or destroyed
  #------------------------------------------------------------------------------
  def update_column
    if errors.empty? && db_transition_safety(as_was) == :safe
      klass.connection.change_column(table_name, name, column_type, column_options)
      klass.reset_column_information
      klass.serialize_custom_fields!
    end
  end

  ActiveSupport.run_load_hooks(:fat_free_crm_custom_field, self)
end

app/models/fields/custom_field_datetime_pair.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class CustomFieldDatetimePair < CustomFieldDatePair
  def render(value)
    value && value.strftime(I18n.t("time.formats.mmddhhss"))
  end

  ActiveSupport.run_load_hooks(:fat_free_crm_datetime_pair, self)
end

app/controllers/admin/fields_controller.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class Admin::FieldsController < Admin::ApplicationController
  before_action "set_current_tab('admin/fields')", only: [:index]

  load_resource except: [:create, :subform]

  # GET /fields
  # GET /fields.xml                                                      HTML
  #----------------------------------------------------------------------------
  def index
  end

  # GET /fields/1
  # GET /fields/1.xml                                                    HTML
  #----------------------------------------------------------------------------
  def show
    respond_with(@field)
  end

  # GET /fields/new
  # GET /fields/new.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def new
    @field = Field.new
    respond_with(@field)
  end

  # GET /fields/1/edit                                                   AJAX
  #----------------------------------------------------------------------------
  def edit
    @field = Field.find(params[:id])
    respond_with(@field)
  end

  # POST /fields
  # POST /fields.xml                                                     AJAX
  #----------------------------------------------------------------------------
  def create
    as = field_params[:as]
    @field =
      if as =~ /pair/
        CustomFieldPair.create_pair(params).first
      elsif as.present?
        klass = Field.lookup_class(as).classify.constantize
        klass.create(field_params)
      else
        Field.new(field_params).tap(&:valid?)
      end

    respond_with(@field)
  end

  # PUT /fields/1
  # PUT /fields/1.xml                                                    AJAX
  #----------------------------------------------------------------------------
  def update
    if field_params[:as] =~ /pair/
      @field = CustomFieldPair.update_pair(params).first
    else
      @field = Field.find(params[:id])
      @field.update_attributes(field_params)
    end

    respond_with(@field)
  end

  # DELETE /fields/1
  # DELETE /fields/1.xml                                        HTML and AJAX
  #----------------------------------------------------------------------------
  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    respond_with(@field)
  end

  # POST /fields/sort
  #----------------------------------------------------------------------------
  def sort
    field_group_id = params[:field_group_id].to_i
    field_ids = params["fields_field_group_#{field_group_id}"] || []

    field_ids.each_with_index do |id, index|
      Field.where(id: id).update_all(position: index + 1, field_group_id: field_group_id)
    end

    render nothing: true
  end

  # GET /fields/subform
  #----------------------------------------------------------------------------
  def subform
    field = field_params
    as = field[:as]

    @field = if (id = field[:id]).present?
               Field.find(id).tap { |f| f.as = as }
             else
               field_group_id = field[:field_group_id]
               klass = Field.lookup_class(as).classify.constantize
               klass.new(field_group_id: field_group_id, as: as)
      end

    respond_with(@field) do |format|
      format.html { render partial: 'admin/fields/subform' }
    end
  end

  protected

  def field_params
    params[:field].permit!
  end
end

app/helpers/admin/fields_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module Admin::FieldsHelper
  # Returns the list of :null and :safe database column transitions.
  # Only these options should be shown on the custom field edit form.
  def field_edit_as_options(field = nil)
    # Return every available field_type if no restriction
    options = (field.as.present? ? field.available_as : Field.field_types).keys
    options.map { |k| [t("field_types.#{k}.title"), k] }
  end

  def field_group_options
    FieldGroup.all.map { |fg| [fg.name, fg.id] }
  end
end

app/helpers/fields_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module FieldsHelper
end

app/views/admin/fields/_field.html.haml
%li.highlight.position{:class => field.class.name.underscore, :id => dom_id(field)}
  %span.handle
    = image_tag "sortable.gif"

  .tools
    %small
      = link_to t(:edit), edit_admin_field_path(field), :class => 'edit'
      = link_to_delete(field, :url => admin_field_path(field), :klass_name => 'Field')

  %tt
    %b= field.label
    == (#{t("field_types.#{field.as}.title")})

    = t(:added_ago, value: timeago(field.created_at)).html_safe
    = hook(:field_bottom, self, :field => field) {}

  .edit_field

app/views/admin/fields/_form.html.haml
- @field ||= CustomField.new
- field_group_id ||= @field.field_group_id
- new_field = @field.id.nil?
- url = new_field ? admin_fields_path : admin_field_path
- html_id = new_field ? nil : "edit_field_#{@field.id}"

%div{:class => new_field ? nil : 'remote edit_field'}
  = form_for([:admin, @field], :url => url, :as => :field, :html => {:class => nil, :id => html_id}, :remote => true) do |f|
    = link_to( 'x', '#', :class => 'close', :title => t(:close_form) )
    = f.error_messages

    = hidden_field_tag 'field[field_group_id]', field_group_id, :id => nil

    .section
      %table
        %tr
          %td
            .label.top.req Field label:
            = f.text_field :label, :id => nil

          %td= spacer
          %td
            .label.top.req Field type:
            = select :field, :as, field_edit_as_options(@field), :include_blank => true, :id => nil

      .subform
        = render(:partial => 'admin/fields/subform') unless new_field

    .buttonbar
      - if new_field
        = f.submit t(:create_field), :id => :field_submit
      - else
        = f.submit t(:save_field), :id => :field_submit
      or
      = link_to( t(:cancel), '#', :class => 'cancel' )

app/views/admin/fields/_sort_by.html.haml
- sort_by_menu_items = ["Field name", "Field label", "Field type", "Table name", "Display sequence", "Display block", "Display width", "Max size"].inject([]) do | items, sort_by|
  - items << %Q[{ name: "#{sort_by}", on_select: function() { #{redraw(:sort_by, sort_by.downcase!)} } }]

:plain
  new crm.Menu({
    trigger   : "#sort_by",
    fade      : 500,
    appear    : 500,
    menu_items: [ #{sort_by_menu_items.join(",")} ]
  });

app/views/admin/fields/_subform.html.haml
= fields_for :field, @field do |f|
  - if (as = f.object.as).present? and lookup_context.exists? "#{as}_field", 'admin/custom_fields', true
    = render :partial => "admin/custom_fields/#{as}_field", :locals => {:f => f}
  - else
    = render :partial => "admin/custom_fields/base_field", :locals => {:f => f}

app/views/admin/fields/create.js.haml
- id = "create_field_field_group_#{@field.field_group_id}";
- custom_field_id = "custom_field_#{@field.id}";
- container_id = "fields_field_group_#{@field.field_group_id}";
- create_field_id = "create_field_field_group_#{@field.field_group_id}";
- empty_field_id = "empty_opportunity_field_group_#{@field.field_group_id}"

- if @field.valid?
  $("##{id}_arrow").html(crm.COLLAPSED)
  $('##{container_id}').append('#{ j (render :partial => "field", :collection => [@field]) }')
  $('##{custom_field_id}').effect("highlight", { duration:1500 });
  $("##{create_field_id}").hide();
  $("##{empty_field_id}").hide();
  $('##{container_id}').sortable('reset');
- else
  $('##{id}').html('#{ j render(:partial => "admin/fields/form", :locals => {:field_group_id => @field.field_group_id}) }')
  $('##{id}').effect("shake", { duration:250, distance: 6 });
  $('##{id}').find('input[type="text"]').first().focus()

app/views/admin/fields/destroy.js.haml
- id = dom_id(@field)
- if @field.destroyed?
  $('li##{id}').css('background-color', '#ffe4e1').slideUp(250);
- else
  $('li##{id}').effect("shake", { duration:250, distance: 6});
  $('#flash').html('#{ j flash[:warning] }')
  $(crm.flash('warning'))
  - flash[:warning] = nil

app/views/admin/fields/edit.js.haml
- id = dom_id(@field)
html = $.parseHTML('#{j render(:partial => "admin/fields/form")}')
$('##{id}').find('.edit_field').replaceWith( html )

app/views/admin/fields/index.html.haml
= styles_for :fields

.title
  %span#create_field_title= t(:admin_tab_fields)

.info= t(:admin_fields_info)

.info2= t(:admin_fields_info2)

.inline_tabs
  %ul
    - list_of_entities.each do |entity|
      - asset = entity.downcase
      %li{ "data-tab-class" => asset, :class => ("selected" if entity == 'Contact') }
        = link_to t(entity), "#"

- list_of_entities.each do |entity|
  - asset = entity.downcase
  - klass = asset.classify.constantize
  .fields{ :id => "#{asset}_section", :style => ("display: none;" if asset != 'contact') }

    - create_form_id = "#{asset}_create_field_group"

    .title_tools
      = link_to_inline(create_form_id, new_admin_field_group_path(:klass_name => klass.name), :text => t(:create_field_group))

    .title
      = t(asset)

    .list{ :id => "#{asset}_field_groups", 'data-sortable' =>  sort_admin_field_groups_path(:asset => asset) }
      = render :partial => "admin/field_groups/field_group", :collection => klass.field_groups, :locals => {:asset => asset, :klass => klass}

    .remote{ hidden.merge(:id => create_form_id) }

app/views/admin/fields/show.html.haml
= styles_for :field

#confirm{ hidden }
.title_tools#menu
  = link_to_inline(:edit_field, edit_admin_field_path(@field), :text => "Edit") + " | "
.title#edit_field_title= @field.field_label

%div#edit_field{ hidden }

%tt
  %br
  Label:
  %b
    - if @field.field_label?
      = @field.field_label
  %br
  Name:
  %b
    - if @field.field_name?
      = @field.field_name
  %br
  Table:
  %b
    - if @field.table_name?
      = @field.table_name.pluralize
  %br
  Type:
  %b
    - if @field.field_type?
      = @field.field_type
  %br
  %br
  Created at:
  %b
    = @field.created_at.to_s
  %br
  Updated at:
  %b
    = @field.updated_at.to_s

= hook(:show_field_bottom, self) {}

app/views/admin/fields/update.js.haml
- id = dom_id(@field)
- container_id = "#{@field.klass_name.downcase}_field_groups"

- if @field.errors.empty?
  html = $.parseHTML('#{ j (render :partial => "field", :collection => [@field]) }');
  $('##{id}').replaceWith(html);
  $('##{id}').effect("highlight", { duration:1000 });
  $('##{container_id}').sortable('reset');
- else
  html = $.parseHTML('#{ j(render :partial => "form") }');
  $('##{id}').find('.edit_field').replaceWith( html );
  $('##{id}').effect("shake", { duration:250, distance: 6 });
  $('##{id}').find('input[type="text"]').first().focus();