config/routes.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root to: 'home#index'

  get 'activities' => 'home#index'
  get 'admin'      => 'admin/users#index',       :as => :admin
  get 'login'      => 'authentications#new',     :as => :login
  delete 'logout'  => 'authentications#destroy', :as => :logout
  get 'profile'    => 'users#show',              :as => :profile
  get 'signup'     => 'users#new',               :as => :signup

  get '/home/options',  as: :options
  get '/home/toggle',   as: :toggle
  match '/home/timeline', as: :timeline, via: [:get, :put, :post]
  match '/home/timezone', as: :timezone, via: [:get, :put, :post]
  post '/home/redraw',   as: :redraw

  resource :authentication, except: [:index, :edit]
  resources :comments,       except: [:new, :show]
  resources :emails,         only: [:destroy]
  resources :passwords,      only: [:new, :create, :edit, :update]

  resources :accounts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
      get :autocomplete_account_name
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: [:patch, :put]
      put :reject
    end
  end

  resources :opportunities, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, id: /\d+/ do
    collection do
      post :filter
      match :auto_complete, via: [:get, :post]
    end
    member do
      put :complete
      put :uncomplete
    end
  end

  resources :users, id: /\d+/, except: [:index, :destroy] do
    member do
      get :avatar
      get :password
      match :upload_avatar, via: [:put, :patch]
      patch :change_password
      post :redraw
    end
    collection do
      match :auto_complete, via: [:get, :post]
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete, via: [:get, :post]
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, except: [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete, via: [:get, :post]
        get :options
        get :redraw
        post :sort
        get :subform
      end
    end

    resources :tags, except: [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, as: :custom_fields
    resources :fields, as: :core_fields

    resources :settings, only: :index
    resources :plugins,  only: :index
  end
end

app/controllers/tasks_controller.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class TasksController < ApplicationController
  before_action :require_user
  before_action :set_current_tab, only: [:index, :show]
  before_action :update_sidebar, only: :index

  # GET /tasks
  #----------------------------------------------------------------------------
  def index
    @view = view
    @tasks = Task.find_all_grouped(current_user, @view)

    respond_with @tasks do |format|
      format.xls { render layout: 'header' }
      format.csv { render csv: @tasks.map(&:second).flatten }
      format.xml { render xml: @tasks, except: [:subscribed_users] }
    end
  end

  # GET /tasks/1
  #----------------------------------------------------------------------------
  def show
    @task = Task.tracked_by(current_user).find(params[:id])
    respond_with(@task)
  end

  # GET /tasks/new
  #----------------------------------------------------------------------------
  def new
    @view = view
    @task = Task.new
    @bucket = Setting.unroll(:task_bucket)[1..-1] << [t(:due_specific_date, default: 'On Specific Date...'), :specific_time]
    @category = Setting.unroll(:task_category)

    if params[:related]
      model, id = params[:related].split(/_(\d+)/)
      if related = model.classify.constantize.my.find_by_id(id)
        instance_variable_set("@asset", related)
      else
        respond_to_related_not_found(model) && return
      end
    end

    respond_with(@task)
  end

  # GET /tasks/1/edit                                                      AJAX
  #----------------------------------------------------------------------------
  def edit
    @view = view
    @task = Task.tracked_by(current_user).find(params[:id])
    @bucket = Setting.unroll(:task_bucket)[1..-1] << [t(:due_specific_date, default: 'On Specific Date...'), :specific_time]
    @category = Setting.unroll(:task_category)
    @asset = @task.asset if @task.asset_id?

    if params[:previous].to_s =~ /(\d+)\z/
      @previous = Task.tracked_by(current_user).find_by_id(Regexp.last_match[1]) || Regexp.last_match[1].to_i
    end

    respond_with(@task)
  end

  # POST /tasks
  #----------------------------------------------------------------------------
  def create
    @view = view
    @task = Task.new(task_params) # NOTE: we don't display validation messages for tasks.

    respond_with(@task) do |_format|
      if @task.save
        update_sidebar if called_from_index_page?
      end
    end
  end

  # PUT /tasks/1
  #----------------------------------------------------------------------------
  def update
    @view = view
    @task = Task.tracked_by(current_user).find(params[:id])
    @task_before_update = @task.dup

    if @task.due_at && (@task.due_at < Date.today.to_time)
      @task_before_update.bucket = "overdue"
    else
      @task_before_update.bucket = @task.computed_bucket
    end

    respond_with(@task) do |_format|
      if @task.update_attributes(task_params)
        @task.bucket = @task.computed_bucket
        if called_from_index_page?
          if Task.bucket_empty?(@task_before_update.bucket, current_user, @view)
            @empty_bucket = @task_before_update.bucket
          end
          update_sidebar
        end
      end
    end
  end

  # DELETE /tasks/1
  #----------------------------------------------------------------------------
  def destroy
    @view = view
    @task = Task.tracked_by(current_user).find(params[:id])
    @task.destroy

    # Make sure bucket's div gets hidden if we're deleting last task in the bucket.
    if Task.bucket_empty?(params[:bucket], current_user, @view)
      @empty_bucket = params[:bucket]
    end

    update_sidebar if called_from_index_page?
    respond_with(@task)
  end

  # PUT /tasks/1/complete
  #----------------------------------------------------------------------------
  def complete
    @task = Task.tracked_by(current_user).find(params[:id])
    @task.update_attributes(completed_at: Time.now, completed_by: current_user.id) if @task

    # Make sure bucket's div gets hidden if it's the last completed task in the bucket.
    if Task.bucket_empty?(params[:bucket], current_user)
      @empty_bucket = params[:bucket]
    end

    update_sidebar unless params[:bucket].blank?
    respond_with(@task)
  end

  # PUT /tasks/1/uncomplete
  #----------------------------------------------------------------------------
  def uncomplete
    @task = Task.tracked_by(current_user).find(params[:id])
    @task.update_attributes(completed_at: nil, completed_by: nil) if @task

    # Make sure bucket's div gets hidden if we're deleting last task in the bucket.
    if Task.bucket_empty?(params[:bucket], current_user, @view)
      @empty_bucket = params[:bucket]
    end

    update_sidebar
    respond_with(@task)
  end

  # POST /tasks/auto_complete/query                                        AJAX
  #----------------------------------------------------------------------------
  # Handled by ApplicationController :auto_complete

  # Ajax request to filter out a list of tasks.                            AJAX
  #----------------------------------------------------------------------------
  def filter
    @view = view

    update_session do |filters|
      if params[:checked].true?
        filters << params[:filter]
      else
        filters.delete(params[:filter])
      end
    end
  end

  protected

  def task_params
    params[:task].permit!
  end

  private

  # Yields array of current filters and updates the session using new values.
  #----------------------------------------------------------------------------
  def update_session
    name = "filter_by_task_#{@view}"
    filters = (session[name].nil? ? [] : session[name].split(","))
    yield filters
    session[name] = filters.uniq.join(",")
  end

  # Collect data necessary to render filters sidebar.
  #----------------------------------------------------------------------------
  def update_sidebar
    @view = view
    @task_total = Task.totals(current_user, @view)

    # Update filters session if we added, deleted, or completed a task.
    if @task
      update_session do |filters|
        if @empty_bucket  # deleted, completed, rescheduled, or reassigned and need to hide a bucket
          filters.delete(@empty_bucket)
        elsif !@task.deleted_at && !@task.completed_at # created new task
          filters << @task.computed_bucket
        end
      end
    end

    # Create default filters if filters session is empty.
    name = "filter_by_task_#{@view}"
    unless session[name]
      filters = @task_total.keys.select { |key| key != :all && @task_total[key] != 0 }.join(",")
      session[name] = filters unless filters.blank?
    end
  end

  # Ensure view is allowed
  #----------------------------------------------------------------------------
  def view
    view = params[:view]
    views = Task::ALLOWED_VIEWS
    views.include?(view) ? view : views.first
  end
end

app/helpers/tasks_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module TasksHelper
  # Sidebar checkbox control for filtering tasks by due date -- used for
  # pending and assigned views only.
  #----------------------------------------------------------------------------
  def task_filter_checkbox(view, filter, count)
    name = "filter_by_task_#{view}"
    checked = (session[name] ? session[name].split(",").include?(filter.to_s) : count > 0)
    url = url_for(action: :filter, view: view)
    onclick = %{
      $('#loading').show();
      $.post('#{url}', {filter: this.value, checked: this.checked}, function () {
        $('#loading').hide();
      });
    }
    check_box_tag("filters[]", filter, checked, onclick: onclick, id: "filters_#{filter.to_s.underscore}")
  end

  #----------------------------------------------------------------------------
  def filtered_out?(view, filter = nil)
    name = "filter_by_task_#{view}"
    if filter
      filters = (session[name].nil? ? [] : session[name].split(","))
      !filters.include?(filter.to_s)
    else
      session[name].blank?
    end
  end

  #----------------------------------------------------------------------------
  def link_to_task_edit(task, bucket)
    link_to(t(:edit), edit_task_path(task, bucket: bucket, view: @view, previous: "crm.find_form('edit_task')"),
            method: :get, remote: true)
  end

  #----------------------------------------------------------------------------
  def link_to_task_delete(task, bucket)
    link_to(t(:delete) + "!", task_path(task, bucket: bucket, view: @view),
            method: :delete, remote: true)
  end

  #----------------------------------------------------------------------------
  def link_to_task_complete(pending, bucket)
    onclick = %{$("##{dom_id(pending, :name)}").css({textDecoration: "line-through"});}
    onclick << %{$.ajax("#{complete_task_path(pending)}", {type: "PUT", data: {bucket: "#{bucket}"}});}
  end

  #----------------------------------------------------------------------------
  def link_to_task_uncomplete(task, bucket)
    link_to(t(:task_uncomplete), uncomplete_task_path(task, bucket: bucket, view: @view),
            method: :put, remote: true)
  end

  # Task summary for RSS/ATOM feed.
  #----------------------------------------------------------------------------
  def task_summary(task)
    summary = [task.category.blank? ? t(:other) : t(task.category)]
    if @view != "completed"
      if @view == "pending" && task.user != current_user
        summary << t(:task_from, task.user.full_name)
      elsif @view == "assigned"
        summary << t(:task_from, task.assignee.full_name)
      end
      summary << "#{t(:related)} #{task.asset.name} (#{task.asset_type.downcase})" if task.asset_id?
      summary << if task.bucket == "due_asap"
                   t(:task_due_now)
                 elsif task.bucket == "due_later"
                   t(:task_due_later)
                 else
                   l(task.due_at.localtime, format: :mmddhhss)
      end
    else # completed
      summary << "#{t(:related)} #{task.asset.name} (#{task.asset_type.downcase})" if task.asset_id?
      summary << t(:task_completed_by,
                   time_ago: distance_of_time_in_words(task.completed_at, Time.now),
                   date:     l(task.completed_at.localtime, format: :mmddhhss),
                   user:     task.completor.full_name)
    end
    summary.join(', ')
  end

  #----------------------------------------------------------------------------
  def hide_task_and_possibly_bucket(task, bucket)
    text = "$('##{h dom_id(task)}').remove();\n"
    text << "$('#list_#{h bucket.to_s}').fadeOut({ duration:500 });\n" if Task.bucket_empty?(bucket, current_user, @view)
    text.html_safe
  end

  #----------------------------------------------------------------------------
  def replace_content(task, bucket = nil)
    partial = (task.assigned_to && task.assigned_to != current_user.id) ? "assigned" : "pending"
    html = render(partial: "tasks/#{partial}", collection: [task], locals: { bucket: bucket })
    text = "$('##{dom_id(task)}').html('#{ j html }');\n".html_safe
  end

  #----------------------------------------------------------------------------
  def insert_content(task, bucket, view)
    text = "$('#list_#{bucket}').show();\n"
    html = render(partial: view, collection: [task], locals: { bucket: bucket })
    text << "$('##{h bucket.to_s}').prepend('#{ j html }');\n"
    text << "$('##{dom_id(task)}').effect('highlight', { duration:1500 });\n"
    text.html_safe
  end

  #----------------------------------------------------------------------------
  def tasks_flash(message)
    text = "$('#flash').html('#{ sanitize(message) }');\n"
    text << "crm.flash('notice', true)\n"
    text.html_safe
  end

  #----------------------------------------------------------------------------
  def reassign(task)
    text = "".html_safe
    if @view == "pending" && @task.assigned_to.present? && @task.assigned_to != current_user.id
      text << hide_task_and_possibly_bucket(task, @task_before_update.bucket)
      text << tasks_flash(t(:task_assigned, (h @task.assignee.try(:full_name))) + " (#{link_to(t(:view_assigned_tasks), url_for(controller: :tasks, view: :assigned))})")
    elsif @view == "assigned" && @task.assigned_to.blank?
      text << hide_task_and_possibly_bucket(task, @task_before_update.bucket)
      text << tasks_flash(t(:task_pending) + " (#{link_to(t(:view_pending_tasks), tasks_url)}.")
    else
      text << replace_content(@task, @task.bucket)
    end
    text << refresh_sidebar(:index, :filters)
    text
  end

  #----------------------------------------------------------------------------
  def reschedule(task)
    text = hide_task_and_possibly_bucket(task, @task_before_update.bucket)
    text << insert_content(task, task.bucket, @view)
    text << refresh_sidebar(:index, :filters)
    text
  end
end

app/views/tasks/_empty.html.haml
#empty
  == #{t(:no_tasks, t('no_tasks_' + @view))}.
  - if @view != "completed"
    == #{t :feel_free} #{link_to(t(:create_task_small), new_task_path + "?view=#{@view}", :remote => true)}.

app/views/tasks/_new.html.haml
= simple_form_for(@task, :html => one_submit_only, :remote => true) do |f|
  = link_to_close new_task_path + "?view=#{@view}"
  = hidden_field_tag :view, @view
  = hidden_field_tag "task[user_id]", current_user.id
  = hidden_field_tag "task[asset_id]", "#{@asset.id if @asset}"
  = hidden_field_tag "task[asset_type]", "#{@asset.class if @asset}"

  = render "tasks/top_section",    :f => f
  = render "fields/groups", :f => f

  .buttonbar
    = f.submit t :create_task
    #{t :or}
    = link_to_cancel new_task_path + "?view=#{@view}"

app/views/tasks/_pending.html.haml
%li.highlight[pending]
  - unless pending.category.blank?
    .strip{:class => pending.category}= t(pending.category)
  - else
    .strip.white #{t :other}

  .tools
    = link_to_task_edit(pending, bucket) + " | "
    = link_to_discard(pending) + " | " if shown_on_landing_page?
    = link_to_task_delete(pending, bucket)

  = check_box_tag dom_id(pending, :complete), 1, false, :onclick => link_to_task_complete(pending, bucket)

  .indentwide
    %label{ :id => dom_id(pending, :name) }
      - if pending.user.id != current_user.id
        = t(:task_from, link_to(h(pending.user.full_name), user_path(pending.user))).html_safe << ':'
      = auto_link h(pending.name)
      - if pending.asset_id?
        =t :related
        = link_to(h(pending.asset.name), polymorphic_url(pending.asset))
      &ndash;
    %tt
      - if pending.bucket == "due_asap"
        %span.urgent= t(:task_due_now)

      - elsif pending.bucket == "due_later"
        = t(:task_due_later)

      - else
        - if pending.at_specific_time?
          - if pending.due_at < Time.now
            %span.warn= distance_of_time_in_words(pending.due_at, Time.now)
            = t(:task_overdue)
            = l(pending.due_at.localtime, :format => :mmddhhss)
          - else
            = t(:task_due_in, distance_of_time_in_words(Time.now, pending.due_at.localtime))
            = '(' << l(pending.due_at.localtime, :format => :mmddhhss) << ')'

        - else
          - if pending.due_at < Date.today
            %span.warn= distance_of_time_in_words(pending.due_at, Time.now)
            = t(:task_overdue)
            = l(pending.due_at.localtime.to_date, :format => :mmdd)
          - elsif pending.due_at > Date.today
            = t(:task_due_in, distance_of_time_in_words(Time.now, pending.due_at.localtime.end_of_day))
          - else
            %span.cool= t(:task_due_today)

    - unless pending.background_info.blank?
      %div
        %dt= h(pending.background_info)

app/views/tasks/_related.html.haml
%li.highlight[related]
  - unless related.category.blank?
    .strip{:class => related.category}= t(related.category)
  - else
    .strip{:style => "color:white"} #{t :other}
  %div
    - if related.assigned_to
      = link_to(related.assignee.full_name, user_path(related.assignee))
    - else
      = link_to(related.user.full_name, user_path(related.user))
    = ": " + related.name
    - if related.asset_id?
      == (#{t :related} #{link_to(related.asset.name, polymorphic_url(related.asset))})
    &ndash;
    %tt
      - if related.completed_at
        %span.cool
          = t(:task_completed_ago, distance_of_time_in_words(related.completed_at, Time.now))
      - elsif related.bucket == "due_asap"
        %span.urgent
        == #{t :due_now}.
      - elsif related.bucket == "due_later"
        == #{t :due_later}.
      - elsif related.due_at < Date.today
        %span.warn= distance_of_time_in_words(related.due_at, Date.today)
        == #{t :overdue} #{related.due_at.strftime('%b %e')}
      - elsif related.due_at > Date.today
        = t(:task_due_in, distance_of_time_in_words(Time.now, related.due_at.end_of_day))
      - else
        %span.cool
        == #{t :due_today}.

app/views/tasks/_selector.html.haml
%table{ :cellpadding => 3, :cellspacing => 0, :style => "width: 100%; margin: 2px 0px 10px 0px" }
  %tr
    %td{ :class => "selector left " + (@view == "pending" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{tasks_path}') }
      = t :pending_tab
    %td{ :class => "selector " + (@view == "assigned" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{url_for(:action => :index, :view => "assigned")}') }
      = t :assigned_tab
    %td{ :class => "selector right " + (@view == "completed" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{url_for(:action => :index, :view => "completed")}') }
      = t :completed_tab

app/views/tasks/_sidebar_index.html.haml
.filters#filters
  = render "selector"
  - if @view == "pending" || @view == "assigned"
    - Setting.unroll(:task_bucket).each do |value, key|
      .check_box{:style => "border-bottom: 1px silver dotted;"}
        %div{:style => "float:right;"}
          = @task_total[key]
        = task_filter_checkbox(@view, key, @task_total[key]) << " " << t(value)
  - else # @view == "completed"
    - Setting.unroll(:task_completed).each do |value, key|
      .check_box{:style => "border-bottom: 1px silver dotted;"}
        %div{:style => "float:right;"}
          = @task_total[key]
        = task_filter_checkbox(@view, key, @task_total[key]) << " " << t(value)
  .check_box
    %div{:style => "float:right;"}
      %b= @task_total[:all]
    %b== #{t(:total_tasks, t(@view + '_tasks'))}

app/views/tasks/_tasks.html.haml
= section(object, :tasks)
.log#tasks
  = render "shared/tasks"

app/views/tasks/create.js.haml
- if @task.valid?
  $('#create_task_arrow').html(crm.COLLAPSED);
  $('#create_task').slideUp(250);

  - if called_from_index_page?  # "Classic" [Create Task] form requested from the Tasks page.
    $('#title').html('#{ j (@view == "assigned" ? t(:assigned_tasks) : t(:tasks)) }');

    -# Show flash if assigned to somebody else from the [Pending Tasks] page.
    - if @view == "pending" && @task.assigned_to && @task.assigned_to != current_user.id
      $('#flash').html('#{j t(:task_created)} #{j t(:task_assigned_to, @task.assignee.full_name)} (#{j link_to(t(:view_assigned_tasks), url_for(:view => "assigned"))}).');
      crm.flash('notice', true);
      $('#recently').replaceWith('#{ j render(:partial => "shared/recently") }');

      - # Show flash if assigned to current user from the [Assigned Tasks] page.
    - elsif @view == "assigned" && @task.assigned_to.blank?
      $('#flash').html('#{j t(:task_created)} (#{j link_to(t(:view_pending_tasks), tasks_url)}).');
      crm.flash('notice', true);
      $('#recently').replaceWith('#{ j render(:partial => "shared/recently") }');

    - else # Show newly created task by inserting its div into appropriate bucket; then update tasks sidebar.
      - bucket = @task.computed_bucket
      $('#list_#{bucket}').show();
      $('##{bucket}').before('#{ j render(:partial => @view, :collection => [ @task ], :locals => { :bucket => bucket }) }');
      $('##{dom_id(@task)}').effect("highlight", { duration:1500 });
      = refresh_sidebar(:index, :filters)

    crm.flick('empty', 'remove');

  - else # Inline [Create Task] form reqested from any of the core asset landing pages.
    $('#create_task_title').html('#{ j t(:tasks) }');
    - partial = (@task.assigned_to && @task.assigned_to != current_user.id) ? "assigned" : "pending"
    $('#tasks').prepend('#{ j render(:partial => "tasks/#{partial}", :collection => [@task], :locals => { :bucket => nil }) }');
    $('##{dom_id(@task)}').effect("highlight", { duration:1500 });
    $('#recently').replaceWith('#{ j render(:partial => "shared/recently") }');

- else # Couldn't create the task -- validation failed.
  $('#create_task').effect("shake", { duration:250, distance: 6 });
  $('#task_name').focus();
  $('#new_task input[type=submit]').enable();

app/views/tasks/destroy.js.haml
$('##{dom_id(@task)}').slideUp(250);

- if @empty_bucket
  $('#list_#{@empty_bucket}').fadeOut({ duration:500 });

- if called_from_index_page?
  = refresh_sidebar(:index, :filters)

app/views/tasks/filter.js.haml
- if params[:checked] == 'true'
  $('#list_#{j params[:filter]}').show();
- else
  $('#list_#{j params[:filter]}').hide();

app/views/tasks/index.html.haml
= styles_for :task

- if @view == "completed"
  - buckets = Setting.unroll(:task_completed)
  .title
    = t(:completed_tasks)
    = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
- else
  - buckets = Setting.unroll(:task_bucket)
  = render "title"

.log#tasks
  - buckets.each do |value, key|
    %div{ hidden_if(filtered_out?(@view, key)), :id => "list_#{key}" }
      %h3{:class => key}= t(value)
      .bucket{:id => key}= render :partial => @view, :collection => @tasks[key] || [], :locals => { :bucket => key }
  - if @tasks.values.flatten.blank?
    = render "empty"

#export= render "shared/export"

app/views/tasks/new.js.haml
crm.flick('empty', 'toggle');
crm.flip_form('create_task');

- unless params[:cancel].true?
  $('#create_task').html('#{ j render(:partial => "new") }');
  crm.set_title('create_task', '#{j t(:create_task) }');
- else
  crm.set_title('create_task', '#{ @view == "assigned" ? t(:assigned_tasks) : t(:tasks) }');

app/views/tasks/uncomplete.js.haml
- if @task.errors.empty?
  $('##{dom_id(@task)}').slideUp(250);

  - if @empty_bucket
    $('#list_#{@empty_bucket}').fadeOut({ duration:500 });

  - if called_from_index_page?
    = refresh_sidebar(:index, :filters)
- else # Errors
  $('##{dom_id(@task)}').effect("shake", { duration:250, distance: 6 });
  $('#task_name').focus();
  $('#task_submit').enable();

app/views/tasks/update.js.haml
- if @task.errors.empty?

  - if !called_from_index_page?
    -# If it's not Tasks tab then we just reload appropriate
    -# partial with the new task, and update recent items.
    = replace_content(@task)
    $('#recently').replaceWith('#{ j render(:partial => "shared/recently") }');
  - else
    - if @task.assigned_to != @task_before_update.assigned_to
      = reassign(@task)
    - elsif @task.bucket != @task_before_update.bucket
      = reschedule(@task)
    - else
      = replace_content(@task, @task.bucket)

- else # Errors
  $('##{dom_id(@task)}').effect("shake", { duration:250, distance: 6 });
  $('#task_name').focus();
  $('#task_submit').enable();